const mongoose = require('mongoose');

const paymentSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  petIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Pet' }],
  kind: { type: String, enum: ['membership', 'tag'], required: true },
  amountInCents: { type: Number, required: true },
  currency: { type: String, default: 'ZAR' },
  membership: { type: mongoose.Schema.Types.ObjectId, ref: 'Membership', default: null },
  tagType: { type: String, default: null },
  petDraft: {
    name: { type: String, default: null },
    species: { type: String, default: null },
    breed: { type: String, default: null },
    age: { type: Number, default: null },
    gender: { type: String, default: null },
    color: { type: String, default: null },
    size: { type: String, default: null },
    dateOfBirth: { type: Date, default: null },
    spayedNeutered: { type: Boolean, default: false },
    trainingLevel: { type: String, default: null },
    weight: { type: Number, default: null },
    microchipNumber: { type: String, default: null },
    photoUrl: { type: String, default: null },
  },
  packageType: { type: String },
  shipping: {
    name: { type: String, default: null },
    surname: { type: String, default: null },
    email: { type: String, default: null },
    contact: { type: String, default: null },
    address: {
      street: { type: String, default: null },
      city: { type: String, default: null },
      province: { type: String, default: null },
      postalCode: { type: String, default: null },
      country: { type: String, default: null },
    },
  },
  fulfillment: {
    provider: { type: String, enum: ['pudo'], default: 'pudo' },
    status: {
      type: String,
      enum: ['unfulfilled', 'processing', 'submitted', 'shipped', 'delivered', 'cancelled'],
      default: null,
    },
    notes: { type: String, default: null },
    pudo: {
      shipmentId: { type: String, default: null },
      trackingNumber: { type: String, default: null },
      status: { type: String, default: null },
      labelUrl: { type: String, default: null },
      lastSyncedAt: { type: Date, default: null },
    },
    createdAt: { type: Date, default: null },
    updatedAt: { type: Date, default: null },
    submittedAt: { type: Date, default: null },
    shippedAt: { type: Date, default: null },
    deliveredAt: { type: Date, default: null },
  },
  status: { type: String, enum: ['pending', 'successful', 'failed'], default: 'pending' },
  yocoChargeId: { type: String },
  yocoCheckoutId: { type: String, default: null },
  processedAt: { type: Date, default: null },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Payment', paymentSchema);
